#!/usr/bin/env python3
# Regenerates digits.mod and expected (not run by the test). Out.LongReal and
# Out.Real print the correctly rounded digits of the exact value; Python's %e
# (the C library's printf, correctly rounded, ties to even on exact ties) is
# the oracle. For each value and field width n the layout is Out's: d digits
# generated (d = max(dr, 15) for a LONGREAL, max(dr, 6) for a REAL, dr = n - 6
# or n - 5 capped at 17 or 9), then trailing zeros dropped while d > max(dr,
# 2). Leading blanks are stripped from both sides (the field width is Out's
# own, tested elsewhere). Run: python3 generate.py
import random, struct
random.seed(20260920)

def literal(v, single=False):
    if single:
        t = '%.9g' % v
        m, _, e = t.partition('e')
        if '.' not in m: m += '.0'
        return m + 'E' + (e.lstrip('+') if e else '0')
    t = repr(v)
    m, _, e = t.partition('e')
    if '.' not in m: m += '.0'
    return m + 'D' + (e.lstrip('+') if e else '0')

def fmt(v, n, long):
    neg = str(v).startswith('-') or (v == 0 and struct.pack('>d', v)[0] & 0x80)
    if neg: n -= 1
    dr = n - (6 if long else 5)
    dr = min(dr, 17 if long else 9)
    d = max(dr, 15 if long else 6)
    if v == 0:
        digits = '0' * d; e10 = 0
    else:
        t = '%.*e' % (d - 1, abs(v))
        m, _, e = t.partition('e')
        digits = m.replace('.', ''); e10 = int(e)
    dr = max(dr, 2)
    while d > dr and digits.endswith('0') and len(digits) > 1:
        digits = digits[:-1]; d -= 1
    if len(digits) < 2: digits += '0'
    ex = ('%+04d' if long else '%+03d') % e10 if v != 0 else ('+000' if long else '+00')
    return ('-' if neg else '') + digits[0] + '.' + digits[1:] + ('D' if long else 'E') + ex

longs = [0.1, 0.2, 0.3, 1.0, 1.5, 3.14159265358979, 123.456, 1e22, 1e23, 8.41e21,
         5e-324, 1e-323, 2.2250738585072014e-308, 2.2250738585072009e-308,
         1.7976931348623157e308, 2.0**-24, 2.0**-20, 2.0**-30, 2.0**60, 2.0**100,
         0.5, 0.125, 9007199254740993.0, 1e15, 1e16, 1e17, 999999999999999.9,
         9.999999999999999e22, 0.99999999999999999, 1e-5, 0.0, -0.0, -1.5, -1e300,
         5.9604644775390625e-08, 4.35, 100.0, 1e100, 1e-100, 12345.678901234567]
for _ in range(120):
    bits = random.getrandbits(64)
    v = struct.unpack('>d', struct.pack('>Q', bits))[0]
    if v != v or abs(v) == float('inf'): continue
    longs.append(v)
singles = [0.1, 0.5, 1.0, 3.0e38, 1.0e-45, 1.17549435e-38, 16777217.0, 123.456, -2.5, 0.0]
for _ in range(60):
    bits = random.getrandbits(32)
    v = struct.unpack('>f', struct.pack('>I', bits))[0]
    if v != v or abs(v) == float('inf'): continue
    singles.append(v)
widths_long = [24, 22, 21, 10, 0]
widths_short = [14, 12, 8, 0]
out = ['MODULE digits;',
       '  (* Phase 11 step 2 (inventory A3): Out.LongReal / Out.Real print the',
       '     correctly rounded digits. Generated by generate.py; see the header there. *)',
       '  IMPORT Out;', '  PROCEDURE L(x: LONGREAL; n: INTEGER); BEGIN Out.LongReal(x, n); Out.Ln END L;',
       '  PROCEDURE S(x: REAL; n: INTEGER); BEGIN Out.Real(x, n); Out.Ln END S;', 'BEGIN']
exp = []
for v in longs:
    for n in widths_long:
        out.append('  L(%s, %d);' % (literal(v), n)); exp.append(fmt(v, n, True))
for v in singles:
    vs = struct.unpack('>f', struct.pack('>f', v))[0]
    for n in widths_short:
        out.append('  S(%s, %d);' % (literal(vs, True), n)); exp.append(fmt(vs, n, False))
out.append('END digits.')
open('digits.mod', 'w').write('\n'.join(out) + '\n')
open('expected', 'w').write('\n'.join(exp) + '\n')
print(len(exp), 'lines')
