#!/usr/bin/env python3
# Regenerates realparse.mod and expected (not run by the test): each literal
# is folded in a CONST (c * 1.0D0 drops the numeral text, leaving only the
# value ConstantEvaluator.ParseReal read), and stored to a LONGREAL
# variable, whose IR is the value's exact bits. Python's float() is correctly
# rounded, so it is the oracle. Run: python3 generate.py
import random, struct
random.seed(20260920)
lits = """0.1D0 0.2D0 0.3D0 1.5D0 3.14159265358979D0 123.456D0 1D22 1D23 8.41D21 5D-324
2.2250738585072011D-308 2.2250738585072014D-308 2.2250738585072012D-308
1.7976931348623157D308 1.797693134862315807D308 1.7976931348623158D308
9007199254740993D0 9007199254740992D0 9007199254740994D0 9007199254740995D0
9007199254740993.0000000001D0 9007199254740992.9999999999D0
4.9406564584124654D-324 2.4703282292062327D-324 2.4703282292062328D-324
1.0D-323 1.5D-323 7.4109846876186981626D-324 7.4109846876186981627D-324
1.00000000000000011102230246251565404236316680908203125D0
1.00000000000000011102230246251565404236316680908203126D0
1.00000000000000011102230246251565404236316680908203124D0
0.5D0 2D0 1D0 1D1 1D15 1D16 1D17 4.35D0 0.000001D0 1D-5 123456789012345678901234567890D0
2.99792458D8 6.02214076D23 1.602176634D-19 6.62607015D-34 2.718281828459045235360287D0
1.1D0 2.2D0 3.3D0 0.7D0 100D0 5D-1 25D-2 1D308 1D-307 4.4501477170144023D-308
8.98846567431158D307 8.988465674311580D307 1.5D300 3.7D-320 6.9D-310 1.234567890123456789D-100""".split()
lits = [l if '.' in l else l.replace('D', '.0D') for l in lits]
for _ in range(300):
    nd = random.choice([1,2,5,10,15,16,17,18,19,20,25])
    digits = ''.join(random.choice('0123456789') for _ in range(nd))
    digits = digits[0].replace('0','7') + digits[1:]
    pos = random.randint(1, nd)
    mant = digits[:pos] + ('.' + digits[pos:] if pos < nd else '.0')
    exp = random.choice([random.randint(-30,30), random.randint(-320,300)])
    lits.append('%sD%d' % (mant, exp))
out = ['MODULE realParse;', '  (* Phase 11 step 2 (inventory A2): ConstantEvaluator.ParseReal is correctly',
       '     rounded. Generated by generate.py; see the header there. *)', '  CONST']
for i, l in enumerate(lits):
    out.append('    c%d = %s * 1.0D0;' % (i, l))
out.append('  VAR v: LONGREAL;')
out.append('BEGIN')
for i in range(len(lits)):
    out.append('  v := c%d;' % i)
out.append('END realParse.')
open('realparse.mod', 'w').write('\n'.join(out) + '\n')
exp = []
for l in lits:
    f = float(l.replace('D', 'e'))
    exp.append('store double 0x%016X' % struct.unpack('>Q', struct.pack('>d', f))[0])
open('expected', 'w').write('\n'.join(exp) + '\n')
print(len(lits), 'literals')
