"""What each of voc's modules is for, by module name: read from the header comments
of voc's sources (Phase 12 step 3, 2026-09-27). A module added to voc needs a line here;
write_tables.py stops on one without."""

PURPOSES = {
# runtime
'Files':'Oberon files and riders over Unix files (Oakwood Files plus voc extras: typed Read/Write, search path, GetDate)',
'Heap':'voc\'s heap and garbage collector; module list; finalization',
'In':'Oakwood formatted input from standard input',
'Math':'Oakwood REAL mathematics (from OOC LowReal/RealMath)',
'MathL':'Oakwood LONGREAL mathematics (from OOC LowLReal/LRealMath)',
'Modules':'module list, commands, argc/argv, HALT/ASSERT handling',
'Oberon':'stub of the Oberon system module: Log text, Par (command parameters)',
'Out':'Oakwood formatted output to standard output',
'Platform':'the OS layer: files, time, environment, process, signals (Unix and Windows variants)',
'Reals':'REAL/LONGREAL to and from digits, exponent access (ETH style)',
'Strings':'Oakwood string operations',
'Texts':'Oberon texts, readers, scanners, writers over Files (Oberon system style, no display)',
'VT100':'ANSI/VT100 terminal escape sequences',
# v4
'Args':'command-line arguments and environment (Ofront/V4 style)',
'Console':'unbuffered text output to standard output (Ofront style)',
'Printer':'PostScript printer driver of Oberon V4 (Unix)',
'Sets':'SET operations and output to Texts (V4)',
# misc
'Listen':'singly linked list of integers (teaching example)',
'MersenneTwister':'Mersenne Twister random numbers',
'MultiArrayRiders':'riders over MultiArrays',
'MultiArrays':'multidimensional numeric arrays of any rank',
'crt':'Turbo Pascal CRT-style terminal control over VT100',
# ooc (oo2c 1.x library)
'oocAscii':'names of ASCII control characters',
'oocBinaryRider':'binary input/output of Oberon values over channels',
'oocC':'C data types for interfacing (ILP32/LP64/LLP64 variants; voc builds the host one)',
'oocChannel':'abstract channels, readers and writers (stream I/O framework)',
'oocCharClass':'character classification',
'oocComplexMath':'COMPLEX mathematics (as records)',
'oocConvTypes':'types shared by the string conversion modules',
'oocFilenames':'file name manipulation (obsolete, per its header)',
'oocFiles':'files as channels (voc\'s reimplementation of the oo2c 1.x interface)',
'oocFilesHost':'host file system bindings for oocFiles (voc)',
'oocIntConv':'low-level integer/string conversion',
'oocIntStr':'integer/string conversion',
'oocJulianDay':'dates to and from modified Julian days',
'oocLComplexMath':'LONGCOMPLEX mathematics',
'oocLRealConv':'low-level LONGREAL/string conversion',
'oocLRealMath':'LONGREAL mathematics (ISO style)',
'oocLRealStr':'LONGREAL/string conversion',
'oocLongInts':'simple extended-precision integers',
'oocLowLReal':'properties of LONGREAL (IEEE double): exponent, fraction, ulp',
'oocLowReal':'properties of REAL (IEEE single)',
'oocMsg':'message framework: creation, expansion, conversion to text',
'oocOakMath':'Oakwood Math names over RealMath',
'oocOakStrings':'Oakwood-compliant strings (ooc\'s)',
'oocProgramArgs':'command-line arguments as a read-only channel',
'oocProgramArgsHost':'raw argc/argv access for oocProgramArgs (voc)',
'oocRandomNumbers':'Park-Miller random numbers',
'oocRealConv':'low-level REAL/string conversion',
'oocRealMath':'REAL mathematics (ISO style)',
'oocRealStr':'REAL/string conversion',
'oocRts':'run-time system access: shell command, program name (voc wrapper)',
'oocStrings':'string operations (ISO Modula-2 style)',
'oocStrings2':'more string operations (obsolete, per its header)',
'oocSysClock':'gettimeofday (private; "use Time.GetTime")',
'oocTextRider':'text input/output of Oberon values over channels',
'oocTime':'time and time intervals',
'oocwrapperlibc':'libc wrappers: system, sprintf (inline C)',
# ooc2 (oo2c 2.x)
'ooc2Ascii':'names of ASCII control characters (oo2c 2)',
'ooc2CharClass':'character classification (oo2c 2)',
'ooc2ConvTypes':'types shared by the conversion modules (oo2c 2)',
'ooc2IntConv':'low-level integer/string conversion (oo2c 2)',
'ooc2IntStr':'integer/string conversion (oo2c 2)',
'ooc2LRealConv':'string to LONGREAL conversion (oo2c 2; not built by voc)',
'ooc2Real0':'helpers for the real conversion modules (oo2c 2)',
'ooc2Strings':'string operations (oo2c 2)',
# oocX11
'oocX11':'Xlib interface ([INTERFACE "C"], LINK LIB X11)',
'oocXYplane':'Oakwood XYplane: a pixel plane in an X11 window',
'oocXutil':'Xutil interface',
# pow
'powStrings':'string operations of POW! (Windows Oberon)',
# s3 (ETH Oberon System 3)
'ethBTrees':'B-trees over Files (keys LONGINT or strings)',
'ethBase64':'Base64 encoding and decoding over Files/Texts',
'ethDates':'dates and times, conversion to text',
'ethGZReaders':'reading gzip files (pure Oberon zlib)',
'ethGZWriters':'writing gzip files (pure Oberon zlib)',
'ethMD5':'MD5 message digest',
'ethRandomNumbers':'random numbers (uniform, exponential, ...)',
'ethReals':'REAL/LONGREAL bit access and conversion (ETH Reals)',
'ethSets':'SET operations and output to Texts',
'ethStrings':'string operations and conversions (ETH)',
'ethUnicode':'UCS/UTF-8 conversion',
'ethZip':'zip archives (pure Oberon zlib)',
'ethZlib':'zlib core: constants, streams, adler32/crc32 (pure Oberon)',
'ethZlibBuffers':'buffers for the zlib modules',
'ethZlibDeflate':'deflate compression (pure Oberon)',
'ethZlibInflate':'inflate decompression (pure Oberon)',
'ethZlibReaders':'readers that inflate',
'ethZlibWriters':'writers that deflate',
# ulm (Ulm Oberon Library)
'ulmASCII':'ASCII control characters','ulmAssertions':'general error handling of library routines',
'ulmAsymmetricCiphers':'public-key cipher abstraction','ulmBlockCiphers':'block cipher abstraction',
'ulmCipherOps':'stream cipher helpers','ulmCiphers':'cipher abstraction',
'ulmClocks':'clocks (abstraction over time sources)','ulmConclusions':'turn errors and events into a final message and reaction',
'ulmConditions':'conditions to wait for (coroutine-style scheduling)','ulmConstStrings':'immutable (write-once) strings',
'ulmDisciplines':'attaching extra data to objects (the "discipline" mechanism)','ulmErrors':'events translated to errors',
'ulmEvents':'the event system (raising and handling events)','ulmForwarders':'forwarding operations between objects',
'ulmIEEE':'IEEE floating-point properties (i386 assumptions)','ulmIO':'basic formatted I/O (voc adaptation over Platform)',
'ulmIndirectDisciplines':'disciplines reached through other objects','ulmIntOperations':'generic integer arithmetic operations',
'ulmLoader':'loading and initializing modules (registry)','ulmMC68881':'MC68881 FPU instructions (SunOS 4.1, m68k)',
'ulmNetIO':'portable exchange of base types in persistent data','ulmObjects':'common base type of the library\'s records',
'ulmOperations':'generic arithmetic operations','ulmPersistentDisciplines':'persistent disciplines',
'ulmPersistentObjects':'persistent objects (serialization)','ulmPlotters':'plotter abstraction (setspace, erase, ...)',
'ulmPrint':'printf-style formatted output to streams','ulmPriorities':'priorities of the library\'s event handling',
'ulmProcess':'the current process: name, exit, abort','ulmRandomGenerators':'random number generators',
'ulmReals':'real number utilities','ulmRelatedEvents':'events related to objects',
'ulmResources':'shared objects with cooperative termination','ulmSYSTEM':'Ulm\'s SYSTEM emulated over voc\'s Platform (UNIXCALL, TAS)',
'ulmScales':'scales and measures (time, ...)','ulmServices':'services: installing and calling operations on types',
'ulmSets':'large sets','ulmStreamConditions':'conditions on streams',
'ulmStreamDisciplines':'general-purpose stream disciplines (line terminators, ...)','ulmStreams':'the stream abstraction',
'ulmStrings':'strings as streams','ulmSys':'Linux i386 system call numbers (generated), used as tags by ulmSYSTEM',
'ulmSysConversions':'Oberon records to and from C structures','ulmSysErrors':'Unix errno codes and texts',
'ulmSysIO':'Unix file I/O: open, fcntl, ... (over ulmSYSTEM)','ulmSysStat':'stat(2)/fstat(2) (inline C, struct stat)',
'ulmSysTypes':'Unix system types (C int sizes)','ulmTCrypt':'Trautner\'s key-exchange method',
'ulmTexts':'texts as dynamic strings (streams)','ulmTimeConditions':'conditions that wait for a time',
'ulmTimers':'timers','ulmTimes':'time measures (absolute and relative)',
'ulmTypes':'compiler-dependent types (Int8..Int32, Real32, ...; written for m68k/sparc, adapted)','ulmWrite':'simple output to streams',
# tools
'BrowserCmd':'program: showdef, prints a module\'s interface from its .sym',
'vbeautify':'program: Oberon source beautifier','OCatCmd':'program: prints Oberon texts as plain text',
'HeapDump':'program/debug aid: dumps voc\'s heap','vmake':'program: make for Oberon modules','compatIn':'vmake\'s helper: In-like input over Args',
'Coco':'program: Coco/R parser generator (driver)','CRA':'Coco/R: automaton','CRP':'Coco/R: parser','CRS':'Coco/R: scanner','CRT':'Coco/R: tables','CRX':'Coco/R: code generator',
'IP':'voc\'s test infrastructure: TCP/IP sockets (inline C)','TestClient':'voc\'s test infrastructure: build client','TestCoordinator':'voc\'s test infrastructure: coordinator',
}
