$ ! PLAN.md Phase 16 step 4: ERRBASICS.COM and ERRTRAP.COM, which poc
$ ! -build wrote, run after poc's runtime is assembled; then each image,
$ ! with SYS$ERROR a file, its status, and the file, as test.sh prints the
$ ! LLVM backend's standard error after its status
$ SET NOON
$ MACRO/OBJECT POCRTL.MAR
$ IF .NOT. $STATUS THEN EXIT 1
$ @ERRBASICS
$ WRITE SYS$OUTPUT "== ErrBasics, build status: ", $STATUS
$ DEFINE/USER_MODE SYS$ERROR ERRBASICS.ERR
$ RUN ERRBASICS.EXE
$ WRITE SYS$OUTPUT "status: ", $STATUS
$ IF F$SEARCH("ERRBASICS.ERR") .NES. "" THEN TYPE ERRBASICS.ERR
$ IF F$SEARCH("ERRBASICS.ERR") .NES. "" THEN DELETE/NOLOG ERRBASICS.ERR;*
$ @ERRTRAP
$ WRITE SYS$OUTPUT "== ErrTrap, build status: ", $STATUS
$ DEFINE/USER_MODE SYS$ERROR ERRTRAP.ERR
$ RUN ERRTRAP.EXE
$ WRITE SYS$OUTPUT "status: ", $STATUS
$ IF F$SEARCH("ERRTRAP.ERR") .NES. "" THEN TYPE ERRTRAP.ERR
$ IF F$SEARCH("ERRTRAP.ERR") .NES. "" THEN DELETE/NOLOG ERRTRAP.ERR;*
$ DELETE/NOLOG POCRTL.OBJ;*,ERR.OBJ;*,LINEOUTPUT.OBJ;*,ERRBASICS.OBJ;*,ERRBASICS.OPT;*,ERRBASICS.EXE;*,ERRTRAP.OBJ;*,ERRTRAP.OPT;*,ERRTRAP.EXE;*
$ EXIT 1
