#!/bin/sh
. ../../testenv.sh
# Phase 11 step 2 / doc/history/phase-11-inventory.md B1. Part 1: -emit-interface
# alone writes the folded values for the target and size model it was given,
# so the constants differ between word sizes and between -O2 and -OC. Part 2:
# a whole-program command must not trust a .sym left on disk by a run for a
# different target: lib.sym written for 32-bit is regenerated by a 64-bit
# -emit-llvm-ir, and the client's ARRAY lib.PtrSize is then 8 bytes.
consts() { grep -E '^ *(PtrSize|RecSize|LongMax|SetMax)' "$1" | tr -s ' ' | tr '\n' ' '; echo; }
rm -rf work && mkdir work
cp lib.mod client.mod work/
cd work
: >../result
for flags in "-target i686-unknown-linux-gnu" \
             "-target i686-unknown-linux-gnu -OC" \
             "-target x86_64-unknown-linux-gnu" \
             "-target x86_64-unknown-linux-gnu -OC"
do
  poc $flags -emit-interface lib.mod >/dev/null
  echo "$flags:" >>../result
  consts lib.sym >>../result
done
poc -target i686-unknown-linux-gnu -emit-interface lib.mod >/dev/null
cp lib.sym lib.sym.32
poc -target x86_64-unknown-linux-gnu -emit-llvm-ir client.mod >/dev/null
if cmp -s lib.sym lib.sym.32
then echo "whole-program: lib.sym STALE (32-bit values kept)" >>../result
else echo "whole-program: lib.sym regenerated:" >>../result; consts lib.sym >>../result
fi
grep -o '@client\.a = [^,]*' client.ll >>../result
cd ..
rm -rf work
. ../../testresult.sh
